export const EXCLUDE_STORES_NAME = [
  "DDL_Aged_Debt_History",
  "DDL_Daily_Statistic_Forecast_Summary",
  "DDL_Daily_Statistic_Revenue",
  "DDL_Daily_Statistic_Room_Night",
  "DDL_Daily_Statistic_Summary",
  "DDL_Timezone Definitation",
  "DML_Timezone Definition",
  "sp_export_transaction_chk",
  "xhs_fn_GetDuration2Date",
  "xhs_sp_export_Adyen_Reconciliation - Booking_number",
  "xhs_sp_export_Adyen_Reconciliation",
  "xhs_sp_export_deposit",
  "xhs_sp_export_opening_balance",
  "xhs_sp_export_room_booking",
  "xhs_sp_export_transaction",
  "xhs_sp_exp_all_transaction",
  "xhs_sp_generate_aged_debt",
  "xhs_sp_generate_daily_stat_forecast",
  "xhs_sp_generate_daily_stat_revenue",
  "xhs_sp_generate_daily_stat_room",
  "xhs_sp_generate_daily_stat_summary",
  "xhs_sp_get_daily_stat_forecast",
  "xhs_sp_rpt_aged_debt_details",
  "xhs_sp_rpt_aged_debt_summary allocation",
  "xhs_sp_rpt_aged_debt_summary",
  "xhs_sp_rpt_arrival_list",
  "xhs_sp_rpt_booking_list",
  "xhs_sp_rpt_credit_invoice",
  "xhs_sp_rpt_departure_list",
  "xhs_sp_rpt_deposit_ledger",
  "xhs_sp_rpt_deposit_ledger_posting_date",
  "xhs_sp_rpt_deposit_ledger_summary",
  "xhs_sp_rpt_deposit_movement",
  "xhs_sp_rpt_deposit_transder_atCI",
  "xhs_sp_rpt_get_dep_opening_closing_bal",
  "xhs_sp_rpt_get_opening_closing_bal",
  "xhs_sp_rpt_guest_ledger",
  "xhs_sp_rpt_guest_ledger_movement",
  "xhs_sp_rpt_guest_ledger_summary",
  "xhs_sp_rpt_guest_list",
  "xhs_sp_rpt_inhouse_guest",
  "xhs_sp_rpt_invoice",
  "xhs_sp_rpt_payment_detail",
  "xhs_sp_rpt_polist_VAT",
  "xhs_sp_rpt_reservation_made_yesterday",
  "xhs_sp_rpt_revenue",
  "xhs_sp_rpt_statement_account",
  "xhs_sp_rpt_statement_account_detail",
  "xhs_sp_rpt_transcode_detail",
  "xhs_sp_rpt_transcode_report",
  "xhs_sp_rpt_trial_balance",
  "xhs_sp_rpt_trial_balance_summary",
  "xhs_vw_TAX_BY_POSTING",
  "xhs_vw_TRIAL_BALANCE",
  "xhs_vw_TRIAL_DAY_BY_DAY"
]